In [1]:
import numpy as np
import pandas as pd

In [4]:
dataset = pd.read_csv('holidays_events.csv')

In [5]:
dataset.head()

date     type    locale locale_name                    description  \
0  2012-03-02  Holiday     Local       Manta             Fundacion de Manta   
1  2012-04-01  Holiday  Regional    Cotopaxi  Provincializacion de Cotopaxi   
2  2012-04-12  Holiday     Local      Cuenca            Fundacion de Cuenca   
3  2012-04-14  Holiday     Local    Libertad      Cantonizacion de Libertad   
4  2012-04-21  Holiday     Local    Riobamba      Cantonizacion de Riobamba   

   transferred  
0        False  
1        False  
2        False  
3        False  
4        False

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [18]:
ohe = OneHotEncoder(handle_unknown = 'ignore')

In [19]:
dataset.isna().sum()

date           0
type           0
locale         0
locale_name    0
description    0
transferred    0
dtype: int64

In [24]:
mydict = [{'a': 'John', 'b': 'Marc', 'c': 'Peter', 'd': 'Raph'},
           {'a': '1000', 'b': '2000', 'c': '3000', 'd': '4000' }]
df = pd.DataFrame(mydict)

In [25]:
ohe.fit(df)

OneHotEncoder(handle_unknown='ignore')

In [26]:
ohe.categories_

[array(['1000', 'John'], dtype=object),
 array(['2000', 'Marc'], dtype=object),
 array(['3000', 'Peter'], dtype=object),
 array(['4000', 'Raph'], dtype=object)]

In [27]:
ohe.transform(df).toarray()

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [28]:
df

a     b      c     d
0  John  Marc  Peter  Raph
1  1000  2000   3000  4000

In [30]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [40]:
newDict = le.fit_transform(df.iloc[1,:])

In [41]:
print(newDict)

[0 1 2 3]


In [50]:
newDict = newDict.reshape(2, 2)
newDict

array([[0, 1],
       [2, 3]])

In [51]:
print(ohe.fit_transform(newDict).toarray())

[[1. 0. 1. 0.]
 [0. 1. 0. 1.]]
