In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('../StoreSales/holidays_events.csv')

In [4]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [5]:
ohe = OneHotEncoder(handle_unknown = 'ignore')

In [6]:
dataset.isna().sum()

date           0
type           0
locale         0
locale_name    0
description    0
transferred    0
dtype: int64

In [7]:
mydict = [{'a': 'John', 'b': 'Marc', 'c': 'Peter', 'd': 'Raph'},
           {'a': '1000', 'b': '2000', 'c': '3000', 'd': '4000' }]
df = pd.DataFrame(mydict)

In [8]:
ohe.fit(df)

OneHotEncoder(handle_unknown='ignore')

In [9]:
ohe.categories_

[array(['1000', 'John'], dtype=object),
 array(['2000', 'Marc'], dtype=object),
 array(['3000', 'Peter'], dtype=object),
 array(['4000', 'Raph'], dtype=object)]

In [10]:
ohe.transform(df).toarray()

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [11]:
df

a     b      c     d
0  John  Marc  Peter  Raph
1  1000  2000   3000  4000

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [13]:
newDict = le.fit_transform(df.iloc[1,:])

In [14]:
print(newDict)

[0 1 2 3]


In [15]:
newDict = newDict.reshape(2, 2)
newDict

array([[0, 1],
       [2, 3]])

In [16]:
print(ohe.fit_transform(newDict).toarray())

[[1. 0. 1. 0.]
 [0. 1. 0. 1.]]


In [45]:
datatest = dataset.drop(columns = ['description', 'transferred', 'date'])
datatest = datatest[(datatest.index < 10)]
datatest

type    locale locale_name
0  Holiday     Local       Manta
1  Holiday  Regional    Cotopaxi
2  Holiday     Local      Cuenca
3  Holiday     Local    Libertad
4  Holiday     Local    Riobamba
5  Holiday     Local        Puyo
6  Holiday     Local    Guaranda
7  Holiday  Regional    Imbabura
8  Holiday     Local   Latacunga
9  Holiday     Local     Machala

In [75]:
datatest['type'] = le.fit_transform(datatest['type'])
datatest

type    locale locale_name
0     0     Local       Manta
1     0  Regional    Cotopaxi
2     0     Local      Cuenca
3     0     Local    Libertad
4     0     Local    Riobamba
5     0     Local        Puyo
6     0     Local    Guaranda
7     0  Regional    Imbabura
8     0     Local   Latacunga
9     0     Local     Machala

In [ ]:
numeric_features = [col for col in datatest.columns if datatest[col].dtype=='int64' or datatest[col].dtype=='float64']
numeric_features

['type']

In [77]:
str_features = [col for col in datatest.columns if datatest[col].dtype=='object']
str_features

['locale', 'locale_name']

In [96]:
for col in datatest.columns:
    print(datatest[col].nunique() < 5)

True
True
False


In [97]:
datatest.iloc[0, 2] = np.nan
datatest.iloc[1, 1] = np.nan
datatest

type    locale locale_name
0     0     Local         NaN
1     0       NaN    Cotopaxi
2     0     Local      Cuenca
3     0     Local    Libertad
4     0     Local    Riobamba
5     0     Local        Puyo
6     0     Local    Guaranda
7     0  Regional    Imbabura
8     0     Local   Latacunga
9     0     Local     Machala

In [101]:
from sklearn.impute import SimpleImputer
spi = SimpleImputer(strategy = 'most_frequent', missing_values = np.nan)

In [102]:
print(spi.fit_transform(datatest))

[[0 'Local' 'Cotopaxi']
 [0 'Local' 'Cotopaxi']
 [0 'Local' 'Cuenca']
 [0 'Local' 'Libertad']
 [0 'Local' 'Riobamba']
 [0 'Local' 'Puyo']
 [0 'Local' 'Guaranda']
 [0 'Regional' 'Imbabura']
 [0 'Local' 'Latacunga']
 [0 'Local' 'Machala']]
